# Generated by Django 5.1.3 on 2024-12-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uf',
            options={'verbose_name': 'uf', 'verbose_name_plural': 'ufs'},
        ),
    ]
