# Generated by Django 5.1.3 on 2024-12-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_uf_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.uf'),
        ),
    ]
