# Generated by Django 5.1.3 on 2024-12-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_estudante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='frequencia',
            new_name='Frequencia',
        ),
    ]
