# Generated by Django 5.1.3 on 2024-12-17 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_frequencia_numero_faltas'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='estudante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.estudante', verbose_name='Estudante'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='estudante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='app.estudante', verbose_name='Estudante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequencia',
            name='estudante',
            field=models.ForeignKey(default=0.001, on_delete=django.db.models.deletion.CASCADE, to='app.estudante', verbose_name='Estudante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipo_avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_avaliacao', verbose_name='Tipo de avaliação'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='Frequencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias_estudante', to='app.frequencia', verbose_name='Frequências'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_estudante', to='app.avaliacao', verbose_name='Avaliacoes'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas_estudante', to='app.disciplina', verbose_name='Disciplina'),
        ),
    ]
