# Generated by Django 5.1.3 on 2024-12-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_frequencia_numero_faltas_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='manter_disciplinas',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.turno', verbose_name='Turno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manter_disciplinas',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga horaria'),
        ),
    ]
